### ISSUE TITLE
"Télécharger la sélection" renvoie une erreur 404

### ISSUE THREAD

**Issue by ColinMaudry** [marion-paclot/DECP-app#1]
## Reproduction du problème

1. Je me rends sur http://r.etalab.studio/DECP
2. Sélectionne "ACTION LOGEMENT SERVICES" comme acheteur
3. Je clique sur **Télécharger la sélection**

## Symptômes

L'URL ci-dessous est ouverte mais retourne une erreur 404
```
http://r.etalab.studio/DECP/session/b788ea19201d5cf355ff0e1cee4cf2fc/download/downloadData?w=
```

Si je rafraîchis la page, elle affiche le message suivant :

> ERROR: could not find function "loadWorkbook"

**Comment by marion-paclot** [comment]
Merci. J'en ai profité pour utiliser une nouvelle fonction.
